export const nigerianStates = [
  { id: 1, label: "Abia", value: "abia" },
  { id: 2, label: "Adamawa", value: "adamawa" },
  { id: 3, label: "Akwa Ibom", value: "akwa-ibom" },
  { id: 4, label: "Anambra", value: "anambra" },
  { id: 5, label: "Bauchi", value: "bauchi" },
  { id: 6, label: "Bayelsa", value: "bayelsa" },
  { id: 7, label: "Benue", value: "benue" },
  { id: 8, label: "Borno", value: "borno" },
  { id: 9, label: "Cross River", value: "cross-river" },
  { id: 10, label: "Delta", value: "delta" },
  { id: 11, label: "Ebonyi", value: "ebonyi" },
  { id: 12, label: "Edo", value: "edo" },
  { id: 13, label: "Ekiti", value: "ekiti" },
  { id: 14, label: "Enugu", value: "enugu" },
  { id: 15, label: "Gombe", value: "gombe" },
  { id: 16, label: "Imo", value: "imo" },
  { id: 17, label: "Jigawa", value: "jigawa" },
  { id: 18, label: "Kaduna", value: "kaduna" },
  { id: 19, label: "Kano", value: "kano" },
  { id: 20, label: "Katsina", value: "katsina" },
  { id: 21, label: "Kebbi", value: "kebbi" },
  { id: 22, label: "Kogi", value: "kogi" },
  { id: 23, label: "Kwara", value: "kwara" },
  { id: 24, label: "Lagos", value: "lagos" },
  { id: 25, label: "Nasarawa", value: "nasarawa" },
  { id: 26, label: "Niger", value: "niger" },
  { id: 27, label: "Ogun", value: "ogun" },
  { id: 28, label: "Ondo", value: "ondo" },
  { id: 29, label: "Osun", value: "osun" },
  { id: 30, label: "Oyo", value: "oyo" },
  { id: 31, label: "Plateau", value: "plateau" },
  { id: 32, label: "Rivers", value: "rivers" },
  { id: 33, label: "Sokoto", value: "sokoto" },
  { id: 34, label: "Taraba", value: "taraba" },
  { id: 35, label: "Yobe", value: "yobe" },
  { id: 36, label: "Zamfara", value: "zamfara" },
  { id: 37, label: "Federal Capital Territory", value: "fct" },
];
